title: DevHub
description: un espacio personal para compartir conocimientos y recursos de desarrollo
theme: just-the-docs

#url: https://just-the-docs.github.io
plugins: 
  - emoji

aux_links:
  GitHub: https://github.com/HervoyAncacuraB
  Portfolio: https://portfolio-3e5ce.web.app/home
  CodePen: https://codepen.io/Hervoy-Ancacura
aux_links_new_tab: true

collections:
  001_Ecommerce:
   permalink: "/:collection/:path/"
   output: true
  fundamentos:
   permalink: "/:collection/:path/"
   output: true
  implementacion:
   permalink: "/:collection/:path/"
   output: true

just_the_docs:
  collections:
    fundamentos:
      name: 'Fundamentos'
      nav_exclude: false
    implementacion:
      name: 'Implementacion'
    001_Ecommerce:
      name: '001-Ecommerce'

#       nav_exclude: false

# Explicitly tell GitHub Pages / Jekyll the repository name
repository: "hervoyancacurab/dev-hub"
# Make sure your baseurl is also correct for the new repo name
baseurl: "/dev-hub"